### ISSUE TITLE
Missing Task Dependency

### ISSUE THREAD

**Issue by ricfeatherstone** [ImmobilienScout24/pybuilder_aws_lambda_plugin#25]
Hi,

Trying to use this plugin and failing both on windows and linux with the same error

```
Traceback (most recent call last):
  File "/home/ec2-user/tmp/venv/lib/python2.7/site-packages/pybuilder/cli.py", line 405, in main
    exclude_all_optional=options.exclude_all_optional
  File "/home/ec2-user/tmp/venv/lib/python2.7/site-packages/pybuilder/reactor.py", line 117, in prepare_build
    self.execution_manager.resolve_dependencies(exclude_optional_tasks, exclude_tasks, exclude_all_optional)
  File "/home/ec2-user/tmp/venv/lib/python2.7/site-packages/pybuilder/execution.py", line 470, in resolve_dependencies
    raise MissingTaskDependencyException(task.name, d)
MissingTaskDependencyException: Missing task 'install_build_dependencies' required for task 'package_lambda_code'
------------------------------------------------------------
BUILD FAILED - Missing task 'install_build_dependencies' required for task 'package_lambda_code'
------------------------------------------------------------
Build finished at 2017-03-23 11:30:49
Build took 0 seconds (49 ms)
```

build.py contains

```
from pybuilder.core import use_plugin

use_plugin('pypi:pybuilder_aws_plugin')

default_task = "package_lambda_code"
```

Any idea how to resolve?

Thanks

**Comment by snordhausen** [comment]
You need another plugin:
```
use_plugin('python.install_dependencies')
use_plugin('pypi:pybuilder_aws_plugin')
```
I have updated the documentation to make this more clear.

**Comment by ricfeatherstone** [comment]
Brilliant, thank you
